import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";
import Layout from "@/components/Layout/Layout";
import ModalsProviders from "./Providers/ModalsProviders";
import { ClerkProvider } from "@clerk/nextjs";
import ToasterProvider from "./Providers/ToastProviders";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={cn(
            "min-h-screen bg-background font-sans antialiased",
            inter.className
          )}
        >
          <Providers>
            <ModalsProviders />
            <ToasterProvider />
            {children}
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}
